# Generated by Django 4.1.2 on 2022-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_freelancercategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name="FreelancerCategory",
            new_name="FreelancerSkillsModel",
        ),
    ]
