# Generated by Django 4.1.2 on 2022-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_freelancerfilemodel_locationmodel_skillmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancermodel",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
