# Generated by Django 4.1.2 on 2022-11-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profilemodel_email_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancermodel",
            name="maximum_delivery_time",
            field=models.FloatField(default=1, max_length=30),
        ),
    ]
